### ISSUE TITLE
file-icons package conflict

### ISSUE THREAD

**Issue by hendricha** [smockle/close-on-left#1]
Hey!

Great package, works as advertised, however it makes the icons from the file-icons package disappear from the tabs. Could you add support for it somehow? Thanks

**Comment by hendricha** [comment]
_poke_

**Comment by smockle** [comment]
@hendricha Thanks for using the package, and thanks for opening this issue! I’m sorry I missed it last month, but I just pushed a fix. For some reason I’m getting an error when I try to publish a new version via `apm`, but I’ll post an update when I figure it out.

**Comment by smockle** [comment]
@hendricha The update is published. Uploading to version 0.3.0 in Atom should resolve this issue. Thanks again!
