### ISSUE TITLE
'x' still appears on right

### ISSUE THREAD

**Issue by will1818** [smockle/close-on-left#7]
![screen shot 2016-11-08 at 15 38 36](https://cloud.githubusercontent.com/assets/12893761/20105419/6ff655e2-a5c9-11e6-91bb-34468986af4a.png)

Please see above screenshot, this has happened since the last update:

Please advise what further info you may require? I have attempted a reinstall and reboot but the issue persists.

**Comment by smockle** [comment]
Thanks for reporting this @will1818! Could you please link me to the Atom UI theme you are using?

**Comment by will1818** [comment]
[One Light](https://atom.io/themes/one-light-ui)

**Comment by mliq** [comment]
I just noticed this today for the first time - it occurs only when: 

width of `<atom-workspace> <= 1000px` 

Theme: [One Dark](https://github.com/atom/one-dark-ui).

**Comment by justincorrigible** [comment]
Nice catch!! I'll be submitting a PR to fix this soon. :)

**Comment by smockle** [comment]
Many thanks to @hallaathrad for fixing this! Just published close-on-left version 0.7.2 with the update.
